"""SQLAlchemy 数据模型。"""
from .base import Base, TimestampMixin, GUID
from .basic import (
    Store,
    Route,
    StoreRouteMapping,
    Vehicle,
    VehicleTerrainCapability,
    Driver,
    Warehouse,
)
from .rules import (
    TerrainRule,
    TripRule,
    LoadRule,
    ConstraintConfig,
    ConstraintSnapshot,
)
from .scheduling import (
    SchedulingTask,
    SchedulingTaskSnapshot,
    SchedulingPlan,
    SchedulingPlanDetail,
    SchedulingPlanScore,
    SchedulingConfirmation,
    SchedulingReport,
    ReplanRecord,
)
from .execution import DispatchRecord, ExceptionEvent
from .customer import WxUser, CustomerOrder, PaymentRecord, OrderStatusLog
from .rbac import (
    User,
    Role,
    Permission,
    Menu,
    Dept,
    UserRole,
    RolePermission,
    RoleMenu,
    Dict,
    DictItem,
    SysParam,
    SysLog,
)

__all__ = [
    "Base",
    "TimestampMixin",
    "GUID",
    "Store",
    "Route",
    "StoreRouteMapping",
    "Vehicle",
    "VehicleTerrainCapability",
    "Driver",
    "Warehouse",
    "TerrainRule",
    "TripRule",
    "LoadRule",
    "ConstraintConfig",
    "ConstraintSnapshot",
    "SchedulingTask",
    "SchedulingTaskSnapshot",
    "SchedulingPlan",
    "SchedulingPlanDetail",
    "SchedulingPlanScore",
    "SchedulingConfirmation",
    "SchedulingReport",
    "ReplanRecord",
    "DispatchRecord",
    "ExceptionEvent",
    "WxUser",
    "CustomerOrder",
    "PaymentRecord",
    "OrderStatusLog",
    "User",
    "Role",
    "Permission",
    "Menu",
    "Dept",
    "UserRole",
    "RolePermission",
    "RoleMenu",
    "Dict",
    "DictItem",
    "SysParam",
    "SysLog",
]
